version: 2
env:
  - GO111MODULE=on

builds:
  -
    id: telegram-send-go
    main: ./go
    binary: telegram-send-go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildTime={{ .Date }}
      - -X main.gitCommit={{ .FullCommit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}
  -
    id: telegram-upload-watcher-gui
    main: ./go/gui
    binary: telegram-upload-watcher-gui
    env:
      - CGO_ENABLED=1
    tags:
      - webkit2_41
    hooks:
      before:
        - sh -c "cd go/gui/frontend && npm install && npm run build"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  -
    id: cli
    builds:
      - telegram-send-go
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config.example.ini
  -
    id: gui
    builds:
      - telegram-upload-watcher-gui
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: nerdneilsfield
    name: telegram-upload-watcher

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
