// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<main.SettingsBundle>;

export function PauseRun():Promise<void>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function QueueStats():Promise<Record<string, number>>;

export function ResumeRun():Promise<void>;

export function RunStatus():Promise<main.RunStatus>;

export function SaveSettings(arg1:main.SettingsBundle):Promise<void>;

export function StartRun(arg1:main.SettingsBundle):Promise<void>;

export function StartSendFiles(arg1:main.SettingsBundle,arg2:main.SendFilesRequest):Promise<void>;

export function StartSendImages(arg1:main.SettingsBundle,arg2:main.SendImagesRequest):Promise<void>;

export function StopRun():Promise<void>;
