// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadTelegramConfig(arg1) {
  return window['go']['main']['App']['LoadTelegramConfig'](arg1);
}

export function PauseRun() {
  return window['go']['main']['App']['PauseRun']();
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function QueueStats() {
  return window['go']['main']['App']['QueueStats']();
}

export function ResumeRun() {
  return window['go']['main']['App']['ResumeRun']();
}

export function RunStatus() {
  return window['go']['main']['App']['RunStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StartSendFiles(arg1, arg2) {
  return window['go']['main']['App']['StartSendFiles'](arg1, arg2);
}

export function StartSendImages(arg1, arg2) {
  return window['go']['main']['App']['StartSendImages'](arg1, arg2);
}

export function StopRun() {
  return window['go']['main']['App']['StopRun']();
}
